insert into goods (code, name, description, hot, images, stock, price) values ('party-1', 'Barevné frkačky (5 ks) ', '<br/>Sada barevných frkaček po 5 kusech.<br/><br/>Vhodné od 3 let.', false, 3, 3, 38);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-2', 'Chodící balónek dinosaurus ', '<br/>Chodící balónek ve tvaru dinosaura.<br/><br/>Velikost: 80 x 42 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-3', 'Chodící balónek Jednorožec ', '<br/>Chodící balónek ve tvaru jednorožce.<br/><br/>Velikost: 88 x 60 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-4', 'Chodící balónek Ovce ', '<br/>Chodící balónek ve tvaru Ovce.<br/><br/>Velikost: 58 x 44 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-5', 'Chodící balónek Panda ', '<br/>Chodící balónek ve tvaru pandy.<br/><br/>Velikost: 62 x 42 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-6', 'Chodící balónek Slon ', '<br/>Chodící balónek ve tvaru slona.<br/><br/>Velikost: 80 x 45 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-7', 'Chodící balónek Tučňák ', '<br/>Chodící balónek ve tvaru tučňáka.<br/><br/>Velikost: 50 x 41 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-8', 'Chodící balónek Zajíc ', '<br/>Chodící balónek ve tvaru zajíce.<br/><br/>Velikost: 62 x 60 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-9', 'Chodící balónek žirafa ', '<br/>Chodící balónek ve tvaru žirafy.<br/><br/>Velikost: 91 x 39 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-10', 'Barevný mix nafukovacích balónků ', '<br/>Barevný mix 10 kusů nafukovacích balónků.<br/><br/><br/><br/>', false, 1, 8, 32);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-21', 'Narozeninový balónek 1 modrá ', '<br/>Modrý fóliový balónek ve tvaru čísla jedna.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-22', 'Narozeninový balónek 1 červená ', '<br/>Červený fóliový balónek ve tvaru čísla jedna.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-23', 'Narozeninový balónek 2 modrá ', '<br/>Modrý fóliový balónek ve tvaru čísla dva.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-24', 'Narozeninový balónek 2 červená ', '<br/>Červený fóliový balónek ve tvaru čísla dva.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-25', 'Narozeninový balónek 3 modrá ', '<br/>Modrý fóliový balónek ve tvaru čísla tři.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-26', 'Narozeninový balónek 3 červená ', '<br/>Červený fóliový balónek ve tvaru čísla tři.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-27', 'Narozeninový balónek 4 modrá ', '<br/>Modrý fóliový balónek ve tvaru čísla čtyři.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-28', 'Narozeninový balónek 4 červená ', '<br/>Červený fóliový balónek ve tvaru čísla čtyři.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-29', 'Narozeninový balónek 5 modrá ', '<br/>Modrý fóliový balónek ve tvaru čísla pět.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-30', 'Narozeninový balónek 5 červená ', '<br/>Červený fóliový balónek ve tvaru čísla pět.<br/><br/>Velikost: 81 cm', false, 1, 1, 85);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-31', 'Párty balónek Jednorožec  -  velký ', '<br/>Dekorační balónek ve tvaru jednorožce.<br/><br/>Velikost: 60 x 60 cm', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-32', 'Párty balónek Mickey Mouse MAXI ', '<br/>Obří párty balónek Mickey Mouse.<br/><br/>Velikost: 110 cm', false, 1, 3, 195);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-33', 'Párty balónek Minnie Mouse MAXI ', '<br/>Obří dekorační balónek ve tvaru Minnie Mouse.<br/><br/>Velikost: 110 cm', false, 1, 3, 195);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-34', 'Párty sada  -  Jednorožec ', '<br/>Tématická sada pro oslavu - Jednorožec.<br/><br/>Sada Obsahuje:<br/><br/>8 x papírové talíře<br/>8 x papírové kelímky<br/>8 x brčka<br/>12 x papírové košíčky<br/>20 x ubrousky<br/><br/>1 x ubrus (100 x 180 cm)<br/><br/><br/>', false, 5, 1, 355);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-35', 'Párty sada -  Tlapková patrola ', '<br/>Tématická sada pro oslavu - Tlapková patrola.<br/><br/>Sada Obsahuje:<br/><br/>10 x papírové talíře<br/>10 x papírové kelímky<br/>10 x plastové nože<br/>10 x plastové lžíce<br/>10 x plastové vidličky<br/>10 x brčka<br/>20 x ubrousky<br/><br/>1 x ubrus (108 x 180 cm)<br/>1 x praporky (2 metry)', false, 6, 1, 455);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-36', 'Sada Párty bublifuků', 'Balení obsahuje 7 kusů párty bublifuků v různých barvách.<br/><br/>Velikost: 10.7 x 1.1 cm<br/><br/>Vhodné od 3 let', false, 4, 2, 48);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
