insert into goods (code, name, description, hot, images, stock, price) values ('party-0', 'Narozeninový balónek - 5 červená', 'Červený fóliový balónek ve tvaru čísla pět.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-1', 'Narozeninový balónek - 1 modrá', 'Modrý fóliový balónek ve tvaru čísla jedna.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-2', 'Párty sada - Jednorožec', 'Tématická sada pro oslavu - Jednoroec.<br/><br/><br/>Sada Obsahuje:<br/><br/><br/>8 x papírové talíře<br/>8 x papírové kelímky<br/>8 x brčka<br/>12 x papírové koíčky<br/>20 x ubrousky<br/><br/><br/>1 x ubrus (100 x 180 cm)<br/><br/><br/><br/><br/><br/><br/>', false, 5, 1, 355);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-3', 'Narozeninový balónek - 3 modrá', 'Modrý fóliový balónek ve tvaru čísla tři.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-4', 'Chodící balónek - Tučňák', 'Chodící balónek ve tvaru tučňáka.<br/><br/><br/>Velikost: 50 x 41 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-5', 'Párty balónek - Mickey Mouse MAXI', 'Obří párty balónek Mickey Mouse.<br/><br/><br/>Velikost: 110 cm<br/>', false, 1, 3, 195);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-6', 'Narozeninový balónek - 3 červená', 'Červený fóliový balónek ve tvaru čísla tři.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-7', 'Narozeninový balónek - 4 červená', 'Červený fóliový balónek ve tvaru čísla čtyři.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-8', 'Chodící balónek - Slon', 'Chodící balónek ve tvaru slona.<br/><br/><br/>Velikost: 80 x 45 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-10', 'Narozeninový balónek - 5 modrá', 'Modrý fóliový balónek ve tvaru čísla pět.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-11', 'Narozeninový balónek - 2 červená', 'Červený fóliový balónek ve tvaru čísla dva.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-12', 'Chodící balónek - Žirafa', 'Chodící balónek ve tvaru irafy.<br/><br/><br/>Velikost: 91 x 39 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-13', 'Párty balónek - Jednorožec', 'Dekorační balónek ve tvaru jednoroce.<br/><br/><br/>Velikost: 60 x 60 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-14', 'Chodící balónek - Panda', 'Chodící balónek ve tvaru pandy.<br/><br/><br/>Velikost: 62 x 42 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-15', 'Chodící balónek - Zajíc', 'Chodící balónek ve tvaru zajíce.<br/><br/><br/>Velikost: 62 x 60 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-16', 'Narozeninový balónek - 1 červená', 'Červený fóliový balónek ve tvaru čísla jedna.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-17', 'Narozeninový balónek - 2 modrá', 'Modrý fóliový balónek ve tvaru čísla dva.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-18', 'Chodící balónek - Dinosaurus Rex', 'Chodící balónek ve tvaru dinosaura.<br/><br/><br/>Velikost: 80 x 42 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-19', 'Klasický nafukovací balónek - barevný mix', 'Barevný mix 10 kusů nafukovacích balónků.<br/><br/><br/><br/><br/><br/><br/><br/><br/>', false, 1, 8, 32);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-20', 'Párty sada - Tlapková patrola', 'Tématická sada pro oslavu - Tlapková patrola.<br/><br/><br/>Sada Obsahuje:<br/><br/><br/>10 x papírové talíře<br/>10 x papírové kelímky<br/>10 x plastové noe<br/>10 x plastové líce<br/>10 x plastové vidličky<br/>10 x brčka<br/>20 x ubrousky<br/><br/><br/>1 x ubrus (108 x 180 cm)<br/>1 x praporky (2 metry)<br/>', false, 6, 1, 455);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-21', 'Barevné frkačky', 'Sada barevných frkaček po 5 kusech.<br/><br/><br/>Vhodné od 3 let.<br/>', false, 3, 3, 38);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-22', 'Chodící balónek - Ovce', 'Chodící balónek ve tvaru Ovce.<br/><br/><br/>Velikost: 58 x 44 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-23', 'Narozeninový balónek - 4 modrá', 'Modrý fóliový balónek ve tvaru čísla čtyři.<br/><br/><br/>Velikost: 81 cm<br/>', false, 1, 1, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-24', 'Párty balónek - Minnie Mouse MAXI', 'Obří dekorační balónek ve tvaru Minnie Mouse.<br/><br/><br/>Velikost: 110 cm<br/>', false, 1, 3, 195);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-25', 'Chodící balónek - Jednorožec', 'Chodící balónek ve tvaru jednoroce.<br/><br/><br/>Velikost: 88 x 60 cm<br/>', false, 1, 3, 150);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
