insert into goods (code, name, description, hot, images, stock, price) values ('party-51', 'Dortová fontánka ', '<br/>Velikost: 12 cm', false, 1, 3, 26);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-52', 'Dortové svíčky  -  barevné s proužky ', '<br/>Sada 10 kusů barevných dortových svíček<br/>', false, 0, 10, 35);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-53', 'Narozeninová svíčka 1 modrá ', '<br/>Modrá svíčka ve tvaru čísla 1<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-54', 'Narozeninová svíčka 1 růžová ', '<br/>Růžová svíčka ve tvaru čísla 1<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-55', 'Narozeninová svíčka 2 modrá ', '<br/>Modrá svíčka ve tvaru čísla 2<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-56', 'Narozeninová svíčka 2 růžová ', '<br/>Růžová svíčka ve tvaru čísla 2<br/><br/>Velikost: 7 cm', false, 0, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-57', 'Narozeninová svíčka 3 modrá ', '<br/>Modrá svíčka ve tvaru čísla 3<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-58', 'Narozeninová svíčka 3 růžová ', '<br/>Růžová svíčka ve tvaru čísla 3<br/><br/>Velikost: 7 cm', false, 0, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-59', 'Narozeninová svíčka 4 modrá ', '<br/>Modrá svíčka ve tvaru čísla 4<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-60', 'Narozeninová svíčka 4 růžová ', '<br/>Růžová svíčka ve tvaru čísla 4<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-61', 'Narozeninová svíčka 5 modrá ', '<br/>Modrá svíčka ve tvaru čísla 5<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
insert into goods (code, name, description, hot, images, stock, price) values ('party-62', 'Narozeninová svíčka 5 růžová ', '<br/>Růžová svíčka ve tvaru čísla 5<br/><br/>Velikost: 7 cm', false, 1, 2, 20);
insert into goods_category(category, goods) values ('party', currval('goods_id_seq'));
