name: oslavyadarky.cz CI

on:
  pull-request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package -Pwith-web
      - name: Deploy on server
        env:
          DEPLOY_KEY: ${{ secrets.VS_DEPLOY_KEY }}
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh
          ssh-keyscan oslavyadarky.cz >> ~/.ssh/known_hosts
          ssh-add - <<< "${DEPLOY_KEY}"
          scp c-boot/target/eshop.jar eshop@oslavyadarky.cz:/home/eshop
          ssh eshop@oslavyadarky.cz 'sudo systemctl daemon-reload'
          ssh eshop@oslavyadarky.cz 'sudo systemctl restart eshop'